### ISSUE TITLE
has some errors on NodeJS environment

### ISSUE THREAD

**Issue by hannq** [azaslavsky/domJSON#27] opened 2018-01-11 11:06 UTC
I was tryed to use it on NodeJS environment, and I also used the ['puppeteer'](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md) ,
here is my demo:
`
const puppeteer = require('puppeteer');
const domJSON = require('domjson');
(async () => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('http://lishi.tianqi.com/beijing/201612.html');
    const ulsObjArr = await page.evaluate(() => {
        const uls = document.querySelectorAll('div.tqtongji2 ul');
        return Array.prototype.map.call(uls, function(){
            return domJSON.toJSON(ul)
        });
    });
    console.log('====================================');
    console.log(ulsObjArr);
    console.log('====================================');
    await browser.close();
})();
`
and it has an error: 
              win.location.href    is not defined

Did I have something wrong ? or how can i solve it?

**Comment by azaslavsky** [comment] 2018-01-13 00:38
Closing, as this is a duplicate of #26.  The problem lies with JSDOM and its implementation of the DOM Location API, not with this library.

**Closed as completed by azaslavsky** 2018-01-13 00:38 UTC

**Comment by ibolton336** [comment] 2019-01-15 16:30
I am seeing TypeError: Cannot read property 'href' of undefined when i simply try to import domjson as a dependency in a node script & run the node script.
